name: components_codelab
description: An AngularDart app that simulates a lottery
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.3.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha+4
  angular_components: ^0.9.0-alpha+3
  intl: ^0.14.0

dev_dependencies:
  browser: ^0.10.0
  build_runner: ^0.7.0
  build_test: ^0.9.4
  build_web_compilers: ^0.2.0

dependency_overrides:
  analyzer: ^0.31.0-alpha.1
